In [1]:
import pandas as pd

# Load dataset
data = pd.read_csv('merged_data.csv')
data.head()

,Year,Make,Model,Price,Mileage,Location,Additional,Fuel Type,Car Type,Scraping Time,Source,Car Build,MSRP,Retention Rate,Age,Fuel Type Adjusted
0,2020,Nissan,X-TRAIL,299990,33832,QLD,Drive Away,Petrol,2.5L SUV FWD,1714787251,Drive,SUV,26335,11.391304,4,Conventional
1,2021,Hyundai,i30,45550,17233,QLD,*Excl. Govt. Charges,Petrol,2.0L Hatchback FWD,1714183589,Drive,OTHER,25395,1.793660,3,Conventional
2,2022,Tesla,Model Y,76683,19464,ACT,Drive Away,Electric,SUV RWD,1714183320,Drive,SUV,43415,1.766279,2,Electric
3,2022,Kia,Sportage,59066,18665,SA,Drive Away,Diesel,2.0L Diesel SUV 4WD,1714787862,Drive,SUV,33490,1.763691,2,Conventional
4,2021,Hyundai,i30,43990,41519,QLD,*Excl. Govt. Charges,Petrol,2.0L Hatchback FWD,1711776736,Drive,OTHER,25395,1.732231,3,Conventional

In [2]:
def compute_statistics(df):
    # Group by the adjusted fuel type
    grouped = df.groupby('Fuel Type Adjusted')

    # Calculate statistics
    stats = pd.DataFrame({
        'Number Listed': grouped.size(),
        'Number of Different Makes': grouped['Make'].nunique(),
        'Mean Mileage': grouped['Mileage'].mean(),
        'Std Mileage': grouped['Mileage'].std(),
        'Median Mileage': grouped['Mileage'].median(),
        'Mean Age': grouped['Age'].mean(),
        'Std of Age': grouped['Age'].std(),
        'Median Age': grouped['Age'].median(),
        'Mean Price': grouped['Price'].mean(),
        'Std Price': grouped['Price'].std(),
        'Median Price': grouped['Price'].median(),
    })

    return stats

# Compute statistics for all vehicles
all_vehicle_stats = compute_statistics(data)

# Compute statistics for SUVs specifically
suv_data = data[data['Car Type'].apply(lambda x: 'suv' in str(x).lower())]
suv_stats = compute_statistics(suv_data)

print("All Vehicle Statistics by Fuel Type:")
print(all_vehicle_stats)

print("\nSUV Statistics by Fuel Type:")
print(suv_stats)

All Vehicle Statistics by Fuel Type:
                    Number Listed  Number of Different Makes  Mean Mileage  \
Fuel Type Adjusted
Conventional                 1170                         11  48049.388889
Electric                      771                         11  18753.081712
Hybrid                        715                          8  46609.106294

                     Std Mileage  Median Mileage  Mean Age  Std of Age  \
Fuel Type Adjusted
Conventional        41011.867989         43973.5  3.160684    1.556957
Electric            19090.460195         11335.0  2.317769    1.354716
Hybrid              30644.390748         50556.0  3.197203    1.405867

                    Median Age    Mean Price     Std Price  Median Price
Fuel Type Adjusted
Conventional               3.0  40677.052991  22978.640078       32124.5
Electric                   2.0  82187.787289  45541.506478       67800.0
Hybrid                     3.0  47801.587413  25580.888201       37995.0

SUV Statistics by Fuel Type:
                    Number Listed  Number of Different Makes  Mean Mileage  \
Fuel Type Adjusted
Conventional                  734                          9  38761.151226
Electric                      418                          8  14847.055024
Hybrid                        423                          7  40855.226950

                     Std Mileage  Median Mileage  Mean Age  Std of Age  \
Fuel Type Adjusted
Conventional        39731.213013         32173.5  2.817439    1.612340
Electric            16106.874017          8274.0  2.009569    1.209437
Hybrid              33358.733389         38581.0  2.803783    1.519786

                    Median Age    Mean Price     Std Price  Median Price
Fuel Type Adjusted
Conventional               3.0  45665.459128  25981.215432       37873.0
Electric                   2.0  81765.100478  39870.988441       75366.0
Hybrid                     3.0  58594.040189  28408.003471       47963.0